### ISSUE TITLE
Problems with line height and wrapping in suggestive search

### ISSUE THREAD

**Issue by kallelongjuhani** [City-of-Helsinki/servicemap#175]
See screen cap. On Chrome 36.0.1985.125, OS X.
![screen shot 2014-09-02 at 12 47 55](https://cloud.githubusercontent.com/assets/7520743/4116559/9a323c76-3286-11e4-99c5-430f2668764e.png)

**Comment by tituomin** [comment]
Most of the problem fixed by, now, maybe decrease line height a bit still.
