### ISSUE TITLE
Add language selectors to personalise menu.

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#269]

**Comment by tituomin** [comment]
https://drive.google.com/drive/folders/0Bz_jZaEUKzZ9bzBRVUNHVDJsUXM

**Comment by tituomin** [comment]
Language selection: how to do it on mobile?

**Comment by kallelongjuhani** [comment]
No specific feedback buttons are needed anymore on desktop or on mobile as feedback can be accessed either from the tools menu or the about panel. Language selection should be added to the personalise menu, see design below. The redundant links next to the menu button can still be shown in the desktop version.

https://drive.google.com/open?id=0Bz_jZaEUKzZ9aW03WWpDYzZNblk
