### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by hkotkanen** [City-of-Helsinki/servicemap#277]
I suggest the Helsinki coat of arms. Or was there talk of using a berry, partly because we already have that graphic?

**Comment by tituomin** [comment]
Can't be Helsinki specific. I've been thinking we should just scale down the group of 3 berries from the title page of the tutorial wizard.

**Comment by kallelongjuhani** [comment]
Sorry, I was supposed to do it but have been in holiday mode :)

Please, find a favicon package at
https://drive.google.com/open?id=0Bz_jZaEUKzZ9fk5GZV9VUjZzRndqOG9fYlBPX04zZzUxelVWLUNVX0JiSXVZalF3RmJNaTQ

It should cover everything. Generated by http://realfavicongenerator.net/




Y. t.

Kalle
—
+358 (0)50 357 2769
kalle@saariahojarvenpaa.fi
www.saariahojärvenpää.fi <http://www.xn--saariahojrvenp-eibfa.fi/>
Saariaho Järvenpää
Merimiehenkatu 31
00150 Helsinki

2015-07-30 9:53 GMT+03:00 Timo Tuominen <notifications@github.com>:

**Comment by tituomin** [comment]
Thanks! Closed in b8b3ba5a27088bb7c2e77c76db7a31fbb433d51c
