### ISSUE TITLE
Feature tour has only visual instructions

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#286]
Opastuskierroksella vain visuaalisia ohjeita
Opastuskierroksella on ruudunlukuohjelman käyttäjän kannalta epäinformatiivinen neuvo "Tätä ikonia klikkaamalla näet kaikki aiheen palvelupisteet kartalla". Nuoli osoittaa vasemmalle valikkoon, jossa on ikoni. Ruudunsuurennusohjelmalla tämä on hyvin
hahmotettavissa, mutta ei ruudunlukijalla. Opastuskierroksella on myös muita visuaaliseen hahmottamiseen perustuvia ohjeita, kuten ”tiedot avautuvat vasemmalle” ja ohje esteettömyysprofiilin valinnasta painikkeella, jota ei tarkemmin kuvata sanallisesti.

WCAG: 1.3.3 Aistinvaraiset ominaispiirteet: Ohjeet sisällön ymmärtämiseksi ja hallitsemiseksi eivät riipu yksinomaan komponenttien aistinvaraisista ominaispiirteistä
kuten muoto, koko, visuaalinen sijainti, suunta tai ääni.

**Comment by kallelongjuhani** [comment]
Corrected instructions below together with a few other updates. Swedish translations needed.


### 4/11 Näytä palvelupisteet kartalla

Otsikon vieressä olevaa ikonia klikkamalla näet kaikki aiheen palvelupisteet kartalla. Numero kertoo palvelupisteiden määrän.
–
Click on the icon next to the category name to reveal all the Service Points within the relevant category on the map. The number tells how many Service Points the category has.
–
PÅ SVENSKA


### 5/11 Katso palvelupisteen tiedot

Kun klikkaat kartalla olevan palvelupisteen marjaa, aukeavat palvelupisteen yksityiskohtaiset tiedot.
–
Click on a Service Point berry on the map to browse information about it.
–
PÅ SVENSKA


### 7/11 Valitse omat esteettömyysasetuksesi

Omat asetukset -nappia klikkaamalla voit avata esteettömyys- ja personointiasetukset, joihin kuuluvat kuulo ja näkö, liikkuminen ja kaupunkivalinta.
–
Click the My preferences button to pick custom Accessibility settings. Accessibility options include: Hearing & Sight, Mobility, City.
–
PÅ SVENSKA

### Personalisation menu
Change the personalisation menu title to the less technical "Omat asetukset" – "My preferences" –  PÅ SVENSKA. This should also be the alt title for the button.

### 12/11 The end
Add a button (in the style of the next tip buttons) with the text "Selvä!" (ei ikonia) – "Got it!" – PÅ SVENSKA – that closes the tour.
