### ISSUE TITLE
Font size can't be changed

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#288]
Palvelun käyttöliittymän tekstien kokoa ei voi muuttaa selaimen asetusten kautta. Tämän tulee olla mahdollista ilman käyttöliittymän tai sisällön muuttumista vaikeaksi ymmärtää ja hahmottaa.

WCAG: 1.4.4 Tekstin koon muuttaminen: Lukuun ottamatta tekstitystä ja tekstiä esittäviä kuvia tekstin kokoa voidaan muuttaa ilman avustavaa teknologiaa aina 200 prosenttiin asti ilman sisällön tai toiminnallisuuden menettämistä.

**Comment by villeristi** [comment]
_"Tarkistimme tekstin koon muuttamiseen liittyvän havainnon ja asia on kuten mainitsit eli tekstin kokoa voi muuttaa selaimen asetusten kautta asianmukaisesti.

Virheellinen havainto johtui siitä, että koon muutos näyttäytyi testilaitteistossa verrattain vähäisenä, jolloin heikkonäköisten näkökulmasta palvelua testannut henkilö ei havainnut muutosta riittävän selkeästi. "_
