### ISSUE TITLE
Visual focus contrast too low

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#290]
Tutkituilla sivuilla on käytössä näkyvä kohdistus, joka osoittaa kulloinkin aktiivisena olevan elementin, mutta kohdistuksen vähäisen kontrastin johdosta sitä on suhteellisen vaikea
havaita erityisesti jos käyttäjällä on näkövammasta tai korkeasta iästä johtuvia
näköongelmia.

WCAG: 2.4.7 Näkyvä fokus: Kaikilla näppäimistöltä käytettävillä käyttöliittymillä on
käyttömoodi, jossa näppäimistön fokusindikaattori on näkyvissä.

**Comment by villeristi** [comment]
Waiting input from @kallelongjuhani =>

**Comment by kallelongjuhani** [comment]
Got decent results by adding these rules in a Chrome inspector stylesheet:

*:focus {
    outline-width: 0px !important;
    outline: #0065d9 2px solid !important;
    outline-offset: 3px !important;
    box-shadow: none !important;
    transition: outline 0.25s;
    transition: outline-offset 0.25s;       
}
/* Targets the rounded search field inside the blue bar */
input.form-control.tt-input:focus {
    outline: none !important;
    box-shadow: 0 0 0 2px #fff !important;
    border-color: #0065d9 !important;
    transition: box-shadow 0.25s;
}
