### ISSUE TITLE
Show emergency care details when viewing Helsinki health station

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#293]
Base implementation in `feature-emergency-care-districts` branch.

**Translations**

När den egna hälsostationen är stängd och på natten kl. 22-8 är jour för barn och unga under 16 år på Barnkliniken (hemsidor), och jour för vuxna på Haartmanska sjukhuset (joursidor)

When your health station is closed and in the night between 22-8, emergency care for children and young people under age 16 is provided at Children's Hospital (homepage), and for adults at Haartman Hospital (emergency webpages)

*Sivuhuomautus*: Haartmaniin ohjataan vain eteläisen, keskisen ja läntisen Helsingin asukkaat, muut menevät Malmin sairaalaan. Kai tämä on otettu tuolla kartalla huomioon? Ks. sivu http://www.hel.fi/www/Helsinki/fi/sosiaali-ja-terveyspalvelut/terveyspalvelut/paivystys/

**Comment by tituomin** [comment]
branch feature-emergency-care-division - doesn't work but almost ready. Requires Juha to update the server.

**Comment by juyrjola** [comment]
Server is updated. http://api.hel.fi/servicemap/v1/administrative_division/?type=emergency_care_district now yields the districts.
