### ISSUE TITLE
Make email in feedback optional

### ISSUE THREAD

**Issue by kallelongjuhani** [City-of-Helsinki/servicemap#294]
As noted in the accessibility tests, it is not communicated to the user that email is required to complete the Uservoice feedback form.

If there is no compelling reason for requiring the email address, it should be made optional. In that case, a comment could be added  below it, saying (again, Swedish translation is needed):

Täytä sähköpostiosoitteesi, jos haluat antaa tarvittaessa lisätietoja palautteeseesi liittyen.
–
Please enter your email address, if you are willing to give further details regarding your feedback if required.
–
PÅ SVENSKA

**Comment by tituomin** [comment]
Closed because uservoice won't be used anymore.
