### ISSUE TITLE
Unit's main service is not displayed correctly in service view

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/servicemap#324]
E.g. http://palvelukartta.hel.fi/unit?service=25528

**Comment by Rikuoja** [comment]
Currently the main service is the one highest in the service hierarchy. Perhaps the main service should be rendered according to the query url so it coincides with the query root service, if not the query service itself?

**Comment by Rikuoja** [comment]
Partial solution implemented in pr #413. However, selected the main service to be the highest under the same root still can cause funny results in some cases - but at least now the services are not completely unrelated. Further tweaking can be done depending on how we want to define the "main service".

**Comment by tituomin** [comment]
If there is a matching selected service, I think it should be used directly, to avoid confusion.
