### ISSUE TITLE
Take new logo into use.

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/servicemap#330]

**Comment by kallelongjuhani** [comment]
Happy New Year!

There's now an updated logo here:
https://drive.google.com/open?id=0Bz_jZaEUKzZ9dFV6d1AxSWZfR1k

NB. The following file versions exist for all three languages:
-small.png — For the sticky logo in the SE corner
-small@2x.png — The prior's hdpi version
-medium.png— For the initial logo in the NW corner
-medium@2x.png — The prior's hdpi version
-.svg — What's your guess?

The corresponding favicon files are here:
https://drive.google.com/open?id=0Bz_jZaEUKzZ9fk5GZV9VUjZzRndqOG9fYlBPX04zZzUxelVWLUNVX0JiSXVZalF3RmJNaTQ

**Comment by tituomin** [comment]
Remove beta-word.

**Comment by kallelongjuhani** [comment]
Beta-less version here. For favicon files, please the use the ones above.
https://drive.google.com/open?id=0Bz_jZaEUKzZ9NFFTZkRBbmFEaEk
