### ISSUE TITLE
Add ability to switch to map in mobile

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/servicemap#345]
For search results and units by service listings, only the list view is currently visible. There should be a button to switch between map/listing, preferably at the bottom of the screen.

**Comment by kallelongjuhani** [comment]
An updated design for the result list headings. The design now includes a button for collapsing the list and a special collapsed state of the title bar.

https://drive.google.com/open?id=0Bz_jZaEUKzZ9Njk4b1lTRzg2bnc

The icon font is also updated to include an "icon-list" glyph.
https://drive.google.com/open?id=0Bz_jZaEUKzZ9cTljWU1JSl9aZE0

**Comment by villeristi** [comment]
References #352
