### ISSUE TITLE
Implement drop-down menu for search results sorting criteria

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/servicemap#352]

**Comment by tituomin** [comment]
More details: one of the problems seems to be that the word used as the "current sort" doesn't look like an interactive element and the users don't expect it to be something that can be changed / manipulated.

**Comment by kallelongjuhani** [comment]
An updated design for the result list headings. N.B. the design now includes a button for collapsing the list and a special collapsed state of the title bar.

https://drive.google.com/open?id=0Bz_jZaEUKzZ9Njk4b1lTRzg2bnc

The icon font is also updated to include an "icon-list" glyph.

https://drive.google.com/open?id=0Bz_jZaEUKzZ9cTljWU1JSl9aZE0

This same info is copied to card #

**Comment by villeristi** [comment]
References #342
