### ISSUE TITLE
Show more feedback to user on searches with no results

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/servicemap#491]
When filtering / searching units, always show a "0 results" prompt instead of just the empty map.

**Comment by tituomin** [comment]
This already works for full text searches:
http://localhost:9001/search?q=fysioterapiakoulutus
A similar message should be displayed for units filtered by services, for example:
http://localhost:9001/unit?service=279181

**Comment by vaaralav** [comment]
#492 fixes this eg. in the following case: http://localhost:9001/unit?service=27630 and in the personalisation the user has selected Kauniainen

**Comment by tituomin** [comment]
ok, if you fix the other case too, i'll merge.
